---
# tasks file for kubectl

- name: Add Kubectl repository
  become: true
  copy:
    src: kubernetes.repo
    dest: '/etc/yum.repos.d/kubernetes.repo'
    mode: 0644

- name: Install kubectl
  package:
    name: kubectl
    state: present

- name: Define kubectl user
  set_fact:
    role_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: role_user == ''

- name: Enable kubectl autocompletion
  become: true
  shell: kubectl completion bash >/etc/bash_completion.d/kubectl

- name: create .kube folder
  file:
    path: "{{  kube_home }}"
    state: directory
    owner: "{{ role_user }}"
    group: "{{ role_user }}"

- name: copy kubeconfig files
  copy:
    src: "{{ item }}"
    dest: "{{  kube_home }}/{{ item }}"
    owner: "{{ role_user }}"
    group: "{{ role_user }}"
    mode: 0644
  with_items:
    - "{{ kubeconfig_files }}"